
name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  register-dataset:
    name: Register Dataset
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r MLOps_tourism_project/deployment/requirements.txt

      - name: Upload Dataset to Hugging Face
        env:
          MY_MLOps_Token: ${{ secrets.MY_MLOPS_TOKEN }}
        run: |
          python MLOps_tourism_project/model_building/data_register.py


  data-preparation:
    name: Data Preparation
    needs: register-dataset
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r MLOps_tourism_project/deployment/requirements.txt

      - name: Run Data Preparation
        env:
          MY_MLOps_Token: ${{ secrets.MY_MLOPS_TOKEN }}
        run: |
          python MLOps_tourism_project/model_building/prep.py


  model-training:
    name: Model Training
    needs: data-preparation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r MLOps_tourism_project/deployment/requirements.txt

      - name: Run Model Training
        env:
          MY_MLOps_Token: ${{ secrets.MY_MLOPS_TOKEN }}
        run: |
          python MLOps_tourism_project/model_building/train.py

      - name: Upload MLflow Logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/


  deploy-hosting:
    name: Deploy Streamlit App
    needs: model-training
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r MLOps_tourism_project/deployment/requirements.txt

      - name: Deploy Streamlit App to Hugging Face
        env:
          MY_MLOps_Token: ${{ secrets.MY_MLOPS_TOKEN }}
        run: |
          python MLOps_tourism_project/hosting/hosting.py
